### PR TITLE
added reply on comment with private routes

### PR DESCRIPTION
**Pull request by Aman-Jain1996**
User can now reply on comments
Added private routes to components 
Added 404 page for wrong URL's

### CODE REVIEW

**Review by mdarif6 — APPROVED** [review]
-UI looking very nice.
- code and folder structure is too good.
- merge it

**Review by rahulbakshi4 — APPROVED** [review]
- All the functionalities are working as expected
- Suggestion keep the post button disabled by default until the textbox is empty
Good to merge !

**Review by samyakshah3008 — APPROVED** [review]
Good for approval

**Review by vinc3nati — APPROVED** [review]
Great UI, nice folder structure

**Comment by SadiqZak** [comment]
Good to merge

**Pull request merged**
