### PR TITLE
feat : added static pages using JSX

### PR DESCRIPTION
**Pull request by Aman-Jain1996**
Added all the static pages using JSX with store connection and basic routing

### CODE REVIEW

**Review by Rohanmond — APPROVED** [review]
code lookz good

**Review by ramalingaa — APPROVED** [review]
Code looks clean, no changes required. Good to merge

**Review by vinc3nati — APPROVED** [review]
Structured code, great UI

**Comment by Aman-Jain1996** [comment]
Adding static pages to dev

**Pull request merged**
